### ISSUE TITLE
error of using prsp_score

### ISSUE THREAD

**Issue by bearT2** [favstats/peRspective#11]
Hi! When I run `prsp_score`, I have an error saying 

>  Error in curl::curl_fetch_memory(url, handle = handle) : 
Failed to connect to commentanalyzer.googleapis.com port 443: Operation timed out

I have to use VPN to get access to google. Is it because of my VPN? 

Thank you and appreciate your help!

**Comment by favstats** [comment]
Sounds like that could be the problem. I never encountered this issue so unfortunately I cannot help with that.
