### ISSUE TITLE
prsp_stream fails with numeric text_id

### ISSUE THREAD

**Issue by joon-e** [favstats/peRspective#2]
Hey Fabio,

great package! Just a minor inconvenience: `prsp_stream()` produces an error if `text_id` is numeric:

```r
tibble(
  text_id = c(1L, 2L),
  text = c("Sample text comment", "And another one")
  ) %>% 
  prsp_stream(text = text,
              text_id = text_id,
              safe_output = TRUE,
              score_model = "TOXICITY")
```
```r
Error: Can't join on `x$text_id` x `y$text_id` because of incompatible types.
i `x$text_id` is of type <character>>.
i `y$text_id` is of type <integer>>.
```

**Comment by favstats** [comment]
Good catch! Thanks for reaching out, this certainly shouldn't behave this way. Let me try to fix this!

**Comment by favstats** [comment]
Ok [this commit](https://github.com/favstats/peRspective/commit/e42ed1b33275d1c628c1ffb39fc4b7d771f57987) should fix it.
