### ISSUE TITLE
Automatic error for shorter sleep times

### ISSUE THREAD

**Issue by jbisbee1** [favstats/peRspective#3]
Hi, 

I have an increased quota which allows for more calls than the default 1 per second. However, the peRspective package generates an error for sleeps below 0.7s: "Error in .f(...): Sleeps below 0.7s are sure to hit the ratelimit\n", preventing me from using the increased quota. Is there a way to override this error?

Warmly,
Jim

**Comment by favstats** [comment]
Hi Jim!

I have indeed not considered that people might have different quotas. I turned the error into a warning here on GitHub.

Try installing it that should fix it:

`devtools::install_github("favstats/peRspective")`

**Comment by favstats** [comment]
Update is now on CRAN. Should fix problem for good.
https://github.com/favstats/peRspective/releases/tag/v0.1.1
