### ISSUE TITLE
Error in prsp_stream - dplyr right_join

### ISSUE THREAD

**Issue by IanWRichardson** [favstats/peRspective#6]
I can't get this error to reproduce, but it has happened with two dates of tweets from a very large dataset of tweets.

I'm passing the status_id of the tweets, which is numeric as the text_id. Converting this to numeric doesn't seem to fix the issue.

>  Error: Can't join on `x$text_id` x `y$text_id` because of incompatible types.
>i `x$text_id` is of type <character>>.
i `y$text_id` is of type <double>>.
Backtrace:
     x
>  1. +-global::sourceWithProgress(...)
> 2. | \-base::eval(statements[[idx]], envir = sourceEnv)
>  3. |   \-base::eval(statements[[idx]], envir = sourceEnv)
> 4. |     \-`%>%`(...) Perspective_processing.R:33:4
> 5. +-peRspective::prsp_stream(...)
> 6. | \-`%>%`(...)
> 7. +-dplyr::right_join(...)
> 8. \-dplyr:::right_join.data.frame(...)
> 9.   \-dplyr:::join_mutate(...)
> 10.     \-dplyr:::join_rows(x_key, y_key, type = type, na_equal = na_equal)
> 11.       \-base::tryCatch(...)
> 12.         \-base:::tryCatchList(expr, classes, parentenv, handlers)
> 13.           \-base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 14.             \-value[[3L]](cond)
>Warning message:
The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
Using compatibility `.name_repair`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
Execution halted

Thanks

**Comment by favstats** [comment]
Hi @IanWRichardson!

Have you tried installing the GitHub version? I believe this should fix the issue you are experiencing:

```
#install.packages("remotes")
remotes::install_github("favstats/peRspective")
```

**Comment by favstats** [comment]
The update is now life on CRAN. It should fix the problem for good:
https://github.com/favstats/peRspective/releases/tag/v0.1.1
