### ISSUE TITLE
Sleep below 0.7 still produces error - not warning as per update 

### ISSUE THREAD

**Issue by PicaJohansson** [favstats/peRspective#7]
Hello - thank you for a great package. 

I have been granted an increased QPS and am therefore trying to run prsp_stream and prsp_score with very low sleep. 

I noticed that the package was updated a few months ago to only produce a warning when sleep is set to lower than 0.7, but it still returns an error when I attempt to decrease sleep below this threshold. 

The package version is ‘0.1.0’ (which I believe is the latest one - I installed it about a month ago). 

Any advice on how to resolve this would be much appreciated. 

Many thanks once again!

**Comment by favstats** [comment]
Hi @PicaJohansson!

Have you tried installing the GitHub version? I have yet not find the time to update CRAN:

```
#install.packages("remotes")
remotes::install_github("favstats/peRspective")
```
Hopefully, this should fix the issue.

**Comment by favstats** [comment]
Update is now also on CRAN. Should fix the issue for good.

https://github.com/favstats/peRspective/releases/tag/v0.1.1

**Comment by PicaJohansson** [comment]
Perfect, thank you for your quick response - it all works great!
